In [1]:
import os
import pickle
import numpy as np
import pandas as pd
from tqdm import tqdm, tqdm_notebook
from ph_likes.util import queries
from ph_likes.util import settings

/home/can/anaconda3/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

In [2]:
# df_user = queries.get_phuser_table()
df_post = queries.get_post_table()
df_postlike = queries.get_postlike_table()

In [3]:
df_postlike

                id  post_id  user_id
0                1        1        1
1                2        1        2
2                3        1        3
3                4        1        4
4                5        1        5
5                6        1        6
6                7        1        7
7                8        1        8
8                9        1        9
9               10        1       10
10              11        1       11
11              12        1       12
12              13        1       13
13              14        1       14
14              15        1       15
15              16        1       16
16              17        1       17
17              18        1       18
18              19        1       19
19              20        1       20
20              21        1       21
21              22        1       22
22              23        1       23
23              24        1       24
24              25        1       25
25              26        1       26
26              27        1       27
27              28        1       28
28              29        1       29
29              30        1       30
...            ...      ...      ...
10588205  11639150    63351     4818
10588206  11639262    63350     4818
10588207  11639405    63349     4818
10588208  11639729    63347     4818
10588209  11639946    63346     4818
10588210  11640229    63345    24943
10588211  11640230    63345     4818
10588212  11640916    63341     4818
10588213  11641032    63339     4818
10588214  11641148    63338    20789
10588215  11641149    63338     4818
10588216  11641261    63337     4818
10588217  11641367    63336     4818
10588218  11642023    63332     4818
10588219  11642236    63331    20789
10588220  11642237    63331     4818
10588221  11642489    63330    24943
10588222  11642737    63329    24943
10588223  11642738    63329     4818
10588224  11642739    63329    13321
10588225  11643030    63328    24943
10588226  11643031    63328     4818
10588227  11643290    63327     4818
10588228  11643521    63326    12126
10588229  11643522    63326     4818
10588230  11643818    63325    12126
10588231  11643819    63325     4818
10588232  11644307    63324    24943
10588233  11644308    63324     4818
10588234  11644917    63323     4818

[10588235 rows x 3 columns]

In [4]:
# post_id index
unique_post_ids = df_postlike['post_id'].unique()
post_ids2index = dict(zip(unique_post_ids, range(len(unique_post_ids))))
index2post_ids = dict(zip(post_ids2index.values(), post_ids2index.keys()))

In [5]:
# user_id index
unique_user_ids = df_postlike['user_id'].unique()
user_ids2index = dict(zip(unique_user_ids, range(len(unique_user_ids))))
index2user_ids = dict(zip(user_ids2index.values(), user_ids2index.keys()))

In [6]:
print('len(unique_post_ids):', len(unique_post_ids))
print('len(unique_user_ids):', len(unique_user_ids))

len(unique_post_ids): 63301
len(unique_user_ids): 767110

In [7]:
# create Collaborative Filtering Matrix 
CF = np.full((len(unique_user_ids), len(unique_post_ids)), False, dtype=np.bool)
CF.shape

(767110, 63301)

In [8]:
for i, row in tqdm_notebook(df_postlike.iterrows(), total=len(df_postlike)):
    i_user_id = user_ids2index[row['user_id']]
    i_post_id = post_ids2index[row['post_id']]
    CF[i_user_id, i_post_id] = True

HBox(children=(IntProgress(value=0, max=10588235), HTML(value='')))

# Save

In [9]:
np.save(os.path.join(settings.LOCAL_MODELS_PATH, 'CF.npy'), CF)

In [10]:
# post_ids
pickle.dump(post_ids2index, open(os.path.join(settings.LOCAL_MODELS_PATH, 'post_ids2index.pkl'), 'wb'))
pickle.dump(index2post_ids, open(os.path.join(settings.LOCAL_MODELS_PATH, 'index2post_ids.pkl'), 'wb'))

In [11]:
# user_ids
pickle.dump(user_ids2index, open(os.path.join(settings.LOCAL_MODELS_PATH, 'user_ids2index.pkl'), 'wb'))
pickle.dump(index2user_ids, open(os.path.join(settings.LOCAL_MODELS_PATH, 'index2user_ids.pkl'), 'wb'))